### ISSUE TITLE
Mandar codigo Android

### ISSUE THREAD

**Issue by dev-darenas** [dev-darenas/turnero#14]
por favor recordar @dev-darenas mandar codigo de ejemplo para conectar con impresora

**Comment by FlanSc** [comment]
@dev-darenas

**Comment by dev-darenas** [comment]
1. necesitamos un metodo para encontrar el dispositibo 

   void findBT() {
        try {
            mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();

            if(mBluetoothAdapter == null) {
                statusConnection.setText("No bluetooth adapter available");
            }

            if(!mBluetoothAdapter.isEnabled()) {
                Intent enableBluetooth = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
                startActivityForResult(enableBluetooth, 0);
            }

            Set<BluetoothDevice> pairedDevices = mBluetoothAdapter.getBondedDevices();

            if(pairedDevices.size() > 0) {
                for (BluetoothDevice device : pairedDevices) {
                    statusConnection.setText(device.getName());
                    // BlueTooth Printer is the name of the bluetooth printer device
                    // we got this name from the list of paired devices
                    if (device.getName().equals("BlueTooth Printer")) {
                        mmDevice = device;
                        break;
                    }
                }
            }

            statusConnection.setText("Bluetooth device found.");

        }catch(Exception e){
            e.printStackTrace();
        }
    }
