### ISSUE TITLE
App de turno e impresión por conexión bluetooth 

### ISSUE THREAD

**Issue by FlanSc** [dev-darenas/turnero#17]
Aplicación capaz de recuperar un turno determinado e imprimirlo por medio de bluetooth, Android
![img Android](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/APK_format_icon.png/250px-APK_format_icon.png)

**Comment by FlanSc** [comment]
Integración bluetooth y emparejamiento impresora e impresión escrito.
<H1> Falta:</H1>
- Pruebas impresión en impresora fisica.<br>
- Request HTTP capturar turno (Host  y servidor).<br>
- Diseño XML.<br>

**Comment by Andx1234** [comment]
> Integración bluetooth y emparejamiento impresora e impresión escrito.
> Falta:
> 
> * Pruebas impresión en impresora fisica.
> * Request HTTP capturar turno (Host  y servidor).
> * Diseño XML.

**Comment by Andx1234** [comment]
Ups

**Comment by Authoritt** [comment]
### Falta
- Pruebas de impresión en impresora física.

**Comment by FlanSc** [comment]
Sé termina funcionalidad e impresión del turno
### Falta
Mejor diseño y aplicar logo como icono.
